config/routes.rb
Rails.application.routes.draw do
  resources :white_lists
  post 'white_lists/editar_lista_blanca'

  resources :filtersnos
  post 'filtersnos/consultaFiltros'

  get 'alert_release/index'

  post 'users/expire', to: 'users#expire'
  get 'users/expire', to: 'users#expire'

  get 'user_priority/index'
  get 'user_priority/assignPriority'
  get 'user_priority/assignPriorityPer'
  get 'user_priority/sessionsTran'
  get 'user_priority/groupsPer'

  get 'niv_alertamiento/index'
  post 'niv_alertamiento/exportar_niveles'
  get 'con_gen/index'

  filter :locale


  get 'alertc/par4'
  get 'alertc/par3'
  get 'alertc/par2'
  get 'alertc/par1'
  get 'home/alertaBoton'
  get 'home/pie3'
  get 'home/pie2'
  get 'home/pie1' #, to: 'home#pie1'
  get 'home/contadorSuperior' #, to: 'home#pie1'
  get 'home/totalAlerts'
  get 'home/alertaTransaccional'
  get 'home/alertaPerfiles'
  get 'home/mensajeAlerta'
  get 'home/totalPoratender'
  get 'home/totalAtendidas'



  get 'alertn/alertTran', to: 'alertn#alertTran'
  get 'alertn/observaciones' #, to: 'alertn#observaciones'
  post 'alertn/creacion_observaciones'
  post 'alertn/agregar_a_lista_blanca'
  post 'alertn/bloqueo_de_cuenta'



  #, to: 'alertn#observaciones'
  get 'tbitacora/tbitacora'
  get 'tbitaobse/tbitaobse'
  get 'alertn/alertPer', to: 'alertn#alertPer'
  get 'alertc/busqueda', to: 'alertc#busqueda'

  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :alertn
  resources :alertc
  resources :con_gen
  resources :home, only: [:index, :create]
  resources :trcestatus


   # get '/:locale' => 'home#index'

  # devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  @@byHome = "Home"
  respond_to :html, :js

  def index
    if current_user
      @cu = current_user.profile_id

      if @cu != 0
        @per = Permission.where("view_name = 'Home' and profile_id = ?", @cu)

        @per.each do |permisos|
          @uno = permisos.view_name
          @crearView = permisos.crear
          @editarView = permisos.editar
          @leerView = permisos.leer
          @eliminarView = permisos.eliminar

          if permisos.view_name == @@byHome

            @@crear = permisos.crear
            @@editar = permisos.editar
            @@leer = permisos.leer
            @@eliminar = permisos.eliminar

            @crear = permisos.crear
            @editar = permisos.editar
            @leer = permisos.leer
            @eliminar = permisos.eliminar
          end

        end

        @per_n_tran = Permission.where("view_name = 'New Alert Transaccional' and profile_id = ?", @cu)

        @per_n_tran.each do |permisos|
          @leerNewTran = permisos.leer
        end

        @per_n_per = Permission.where("view_name = 'New Alert Perfiles' and profile_id = ?", @cu)

        @per_n_per.each do |permisos|
          @leerNewPer = permisos.leer
        end

        @per_c_tran = Permission.where("view_name = 'Consult Alert Transaccional' and profile_id = ?", @cu)

        @per_c_tran.each do |permisos|
          @leerConTran = permisos.leer
        end

        @per_c_per = Permission.where("view_name = 'Consult Alert Perfiles' and profile_id = ?", @cu)

        @per_c_per.each do |permisos|
          @leerConPer = permisos.leer
        end


        if ((@@leer == 2))
          # Pruebas
          @countTrans = Tbitacora.where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 1).count
          @countPerf = Tbitacora.where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).count

          @@countTrans = @countTrans
          @@countPerf = @countPerf

          @todas = @countTrans.to_i + @countPerf.to_i
        else
          @sin_permisos = true
        end
      else
        @Without_Permission = 100
        redirect_to new_user_session_path, :alert => t('all.please_continue')
      end

    else
      @Without_Permission = 100
      redirect_to new_user_session_path, :alert => t('all.please_continue')
    end

  end

  def mensajeAlerta

    # @hora_ant = Time.now - 30
    # @fecha = @hora_ant.strftime("%Y-%m-%d")
    # @hora_ant = @hora_ant.strftime("%k:%M:%S.00000")
    #
    # @hora_act = Time.now
    # @hora_act = @hora_act.strftime("%k:%M:%S.00000")
    #
    # @transAnt = Tbitacora.where(:IdTipoReg => 3).where(:IdProducto => 1).where("Hora <= ?", @hora_ant).where(:fecha => @fecha).count
    # @transAct = Tbitacora.where(:IdTipoReg => 3).where(:IdProducto => 1).where("Hora <= ?", @hora_act).where(:fecha => @fecha).count
    #
    # @perAnt = Tbitacora.where(:IdTipoReg => 3).where(:IdProducto => 2).where("Hora <= ?", @hora_ant).where(:fecha => @fecha).count
    # @perAct = Tbitacora.where(:IdTipoReg => 3).where(:IdProducto => 2).where("Hora <= ?", @hora_act).where(:fecha => @fecha).count
    #
    # if @transAct > @transAnt
    #
    #   @mensajeTran = true
    #   @producto = 1
    #
    #   @cantAlertTran = @transAct - @transAnt
    #   @cantAlertTran = @cantAlertTran.to_s
    # else
    #   @mensaje = false
    # end
    #
    # if @perAct > @perAnt
    #
    #   @mensajePer = true
    #   @producto = 2
    #
    #   @cantAlertPer = @perAct - @perAnt
    #   @cantAlertPer = @cantAlertPer.to_s
    # else
    #   @mensaje = false
    # end
    #
    render :partial => "mensajeAlerta"

  end

  def contadorSuperior

    @countTrans = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 1).count
    @countPerf = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).count

    @todas = @countTrans.to_i + @countPerf.to_i

    render :partial => "contadorSuperior"

  end

  def totalPoratender

    @porAtender = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdUsuario => "N/A").count

    render :partial => "totalPoratender"
  end

  def totalAtendidas

    @atendidas = Tbitacora.where(:canceladas => 0).where(:IdTipoReg => 3).where.not(:IdUsuario => "N/A").count

    render :partial => "totalAtendidas"
  end

  def totalAlerts
    @countTrans = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 1).count
    @countPerf = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).count
    render :partial => "totalAlerts"

  end

  def alertaTransaccional

    render :partial => "alertaTransaccional"
  end

  def alertaPerfiles

    render :partial => "alertaPerfiles"
  end

  def pie1
    @cu = current_user.profile_id
    @per = Permission.where("view_name = 'Home' and profile_id = ?", @cu)

    @per.each do |permisos|
      @uno = permisos.view_name
      @crearView = permisos.crear
      @editarView = permisos.editar
      @leerView = permisos.leer
      @eliminarView = permisos.eliminar

      if permisos.view_name == @@byHome

        @@crear = permisos.crear
        @@editar = permisos.editar
        @@leer = permisos.leer
        @@eliminar = permisos.eliminar

        @crear = permisos.crear
        @editar = permisos.editar
        @leer = permisos.leer
        @eliminar = permisos.eliminar
      end

    end

    @per_n_tran = Permission.where("view_name = 'New Alert Transaccional' and profile_id = ?", @cu)

    @per_n_tran.each do |permisos|
      @leerNewTran = permisos.leer
    end

    @per_n_per = Permission.where("view_name = 'New Alert Perfiles' and profile_id = ?", @cu)

    @per_n_per.each do |permisos|
      @leerNewPer = permisos.leer
    end

    @per_c_tran = Permission.where("view_name = 'Consult Alert Transaccional' and profile_id = ?", @cu)

    @per_c_tran.each do |permisos|
      @leerConTran = permisos.leer
    end

    @per_c_per = Permission.where("view_name = 'Consult Alert Perfiles' and profile_id = ?", @cu)

    @per_c_per.each do |permisos|
      @leerConPer = permisos.leer
    end

    @countTrans = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 1).count
    @countPerf = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).count

    render :partial => "pie1"
  end

  def pie2
    @cu = current_user.profile_id
    @per = Permission.where("view_name = 'Home' and profile_id = ?", @cu)

    @per.each do |permisos|
      @uno = permisos.view_name
      @crearView = permisos.crear
      @editarView = permisos.editar
      @leerView = permisos.leer
      @eliminarView = permisos.eliminar

      if permisos.view_name == @@byHome

        @@crear = permisos.crear
        @@editar = permisos.editar
        @@leer = permisos.leer
        @@eliminar = permisos.eliminar

        @crear = permisos.crear
        @editar = permisos.editar
        @leer = permisos.leer
        @eliminar = permisos.eliminar
      end

    end

    @per_n_tran = Permission.where("view_name = 'New Alert Transaccional' and profile_id = ?", @cu)

    @per_n_tran.each do |permisos|
      @leerNewTran = permisos.leer
    end

    @per_n_per = Permission.where("view_name = 'New Alert Perfiles' and profile_id = ?", @cu)

    @per_n_per.each do |permisos|
      @leerNewPer = permisos.leer
    end

    @per_c_tran = Permission.where("view_name = 'Consult Alert Transaccional' and profile_id = ?", @cu)

    @per_c_tran.each do |permisos|
      @leerConTran = permisos.leer
    end

    @per_c_per = Permission.where("view_name = 'Consult Alert Perfiles' and profile_id = ?", @cu)

    @per_c_per.each do |permisos|
      @leerConPer = permisos.leer
    end

    render :partial => "pie2"

  end

  def pie3
    @cu = current_user.profile_id
    @per = Permission.where("view_name = 'Home' and profile_id = ?", @cu)

    @per.each do |permisos|
      @uno = permisos.view_name
      @crearView = permisos.crear
      @editarView = permisos.editar
      @leerView = permisos.leer
      @eliminarView = permisos.eliminar

      if permisos.view_name == @@byHome

        @@crear = permisos.crear
        @@editar = permisos.editar
        @@leer = permisos.leer
        @@eliminar = permisos.eliminar

        @crear = permisos.crear
        @editar = permisos.editar
        @leer = permisos.leer
        @eliminar = permisos.eliminar
      end

    end

    @per_n_tran = Permission.where("view_name = 'New Alert Transaccional' and profile_id = ?", @cu)

    @per_n_tran.each do |permisos|
      @leerNewTran = permisos.leer
    end

    @per_n_per = Permission.where("view_name = 'New Alert Perfiles' and profile_id = ?", @cu)

    @per_n_per.each do |permisos|
      @leerNewPer = permisos.leer
    end

    @per_c_tran = Permission.where("view_name = 'Consult Alert Transaccional' and profile_id = ?", @cu)

    @per_c_tran.each do |permisos|
      @leerConTran = permisos.leer
    end

    @per_c_per = Permission.where("view_name = 'Consult Alert Perfiles' and profile_id = ?", @cu)

    @per_c_per.each do |permisos|
      @leerConPer = permisos.leer
    end

    render :partial => "pie3"

  end

  def alertaBoton
    @hora_ant = Time.now - 30
    @fecha = @hora_ant.strftime("%Y-%m-%d")
    @hora_ant = @hora_ant.strftime("%k:%M:%S.00000")

    @hora_act = Time.now
    @hora_act = @hora_act.strftime("%k:%M:%S.00000")

    render :partial => "alertaBoton"
  end
end

app/views/home/_alertaBoton.html.erb
<button class="btn btn-rounded uti pos" id="btnalert">
  <%
    consulta = 'trcestatus'

    if ActiveRecord::Base.connection.table_exists? consulta

      @hora_act = Time.now
      # @hora_act = Time.now + 33.minutes
      # @hora_act = Time.now + 90.minutes
      @fecha_act = Time.now
      @fecha_act = @fecha_act.strftime("%Y-%m-%d")
      @hora_act = @hora_act.to_time


      sql_query = "select top 1  Id, Fecha, Hora, Reiniciar from trcestatus order by Id desc"
      # sql_query = "select Fecha, Hora from trcestatus order by Id desc limit 1"

      Timeout::timeout(0) {@alerta_existente = ActiveRecord::Base::connection.exec_query(sql_query)}

      if @alerta_existente.present?
        @alerta_existente.each do |al|
          puts "Todos los elementos:::::::: #{al}"

          @fecha_c = al['Fecha']
          @hora = al['Hora']

          @id = al['Id']
          @reiniciar = al['Reiniciar']
        end

        @ultima_fecha = @fecha_c

        @ult_conexion = "#{@fecha_c} " "#{@hora}"

        @ult_conexion = @ult_conexion.to_time

        @tiempo_conexion = ((@hora_act.to_time - @ult_conexion.to_time) / 1.minutes).to_i

        if @fecha_act == @ultima_fecha
          if (@tiempo_conexion < 30)
            @azul = true
          elsif (@tiempo_conexion >= 30) && (@tiempo_conexion <= 60)
            @amarillo = true
          elsif (@tiempo_conexion > 60)
            @rojo = true
          end
        elsif @fecha_act != @ultima_fecha
          @rojo = true
        end
      else
        puts '--------------Error conexión no encontrada'
        @sin_conexion = true
        @amarillo = true
        @ult_conexion = "#{t('all.no_data_tran')}"
      end
    end


  %>
  <i class="fa fa-clock-o"></i> <%= @ult_conexion %>
</button>

<input type="hidden" id="boton">

<script>

    <% if @azul %>
    $(document).ready(function () {
        $('#btnalert').addClass('uti');
        $('#poslab2').hide();
    });
    <% elsif @amarillo %>
    $(document).ready(function () {
        $('#btnalert').removeClass('uti');
        $('#btnalert').addClass('uta');
        $('#poslab2').hide();
    });
    <% elsif @rojo %>
    $(document).ready(function () {
        $('#btnalert').removeClass('uti');
        $('#btnalert').addClass('utr');
        $('#poslab').hide();
        $(document).ready(parpa);

        function parpa() {
            $('#poslab2').fadeIn(500).delay(250).fadeOut(500, parpa)
            setTimeout("$('#poslab2').stop(true,true).css('opacity', 1)", 5000000);
        }
    });

    <% end %>

    //-- Enviar reinicio


    let valReiniciar = "<%= @reiniciar %>",
        idTrcst = "<%= @id %>",
        idUser = "<%= current_user.id %>",
        userName = "<%= current_user.name %>",
        lastName = "<%= current_user.last_name %>";

    (function () {
        // your page initialization code here
        // the DOM will be available here
        let btnUltiAlert = document.getElementById('btnalert');
        $('#boton').val("<%= @reiniciar %>")

        btnUltiAlert.addEventListener('click', function () {

            // alert('Btn alerta Ultimo');

            if (valReiniciar != '1') {
                // alert('El registro esta en 0')

                swal({
                        title: '<%= t('all.alerta') %>',
                        text: `<%= t('all.are_sure') %> ${userName}?`,
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "<%= t('views.mess_apli_swall_confirm')%> ",
                        cancelButtonText: "<%= t('views.mess_apli_swall_cancel')%>",
                        closeOnConfirm: false,
                        closeOnCancel: false
                    },
                    function (isConfirm) {
                        if (isConfirm) {
                            swal({
                                title: '<%= t('all.confirmar') %>',
                                text: '<%= t('all.info_sec') %>',
                                type: "warning",
                                showCancelButton: true,
                                confirmButtonColor: "#DD6B55",
                                confirmButtonText: "<%= t('all.confirmar') %>",
                                cancelButtonText: "<%= t('views.mess_apli_swall_cancel')%>",
                                closeOnConfirm: false,
                                closeOnCancel: false
                            }, function (isConfirm) {
                                if (isConfirm) {

                                    let msgtxt = `Se solicito reinicio del Receptor Central por el usuario ${userName} ${lastName} id ${idUser}`;

                                    $.ajax({
                                        type: "PUT",
                                        beforeSend: function (xhr) {
                                            xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
                                        },
                                        url: `/trcestatus/${idTrcst}.json`,
                                        contentType: "application/json",
                                        dataType: "json",
                                        data: JSON.stringify({
                                            "_method": "update",
                                            //--- Tbitacora
                                            IdUsuario: idUser,
                                            msg: msgtxt
                                        }),
                                        success: function(result, status, xhr){

                                            console.log('entre load ........' + result + status + xhr);
                                            $(".alertaBoton").load('../home/alertaBoton');
                                            $('#btnreinicio').css('display', 'block');

                                            swal({
                                                position: 'top-end',
                                                type: 'success',
                                                title: 'Ok',
                                                text: '<%= t('all.redyReFilter') %>',
                                                showConfirmButton: true,
                                                timer: 5000
                                            });
                                        },
                                        error: function (xhr, ajaxOptions, thrownError) {

                                            swal({
                                                position: 'top-end',
                                                type: 'error',
                                                title: '¡Error!',
                                                text: `Error ${xhr.status} en ${thrownError}`,
                                                showConfirmButton: true,
                                                timer: 3000
                                            });
                                        }
                                    });

                                } else {
                                    swal({
                                        position: 'top-end',
                                        type: 'error',
                                        title: '<%= t('all.actionCanel') %>',
                                        text: '<%= t('all.info_sure') %>',
                                        showConfirmButton: true,
                                        timer: 3000
                                    });
                                }
                            })
                        } else {
                            swal({
                                position: 'top-end',
                                type: 'error',
                                title: '<%= t('all.actionCanel') %>',
                                text: '<%= t('all.info_sure') %>',
                                showConfirmButton: true,
                                timer: 3000
                            });
                        }
                    });

            } else {
                // alert('El registro esta en 1')
                swal({
                    title: '<%= t('all.alerta') %>',
                    text: "<%= t('all.rereFilters') %>",
                    type: 'error',
                    showCancelButton: false,
                    timer: 5000
                })
                $('#btnreinicio').css('display', 'block')
            }
        });
    })();

    let fecha = new Date(),
        horas = `${fecha.getHours()}:${fecha.getMinutes()}:${fecha.getSeconds()}`;


    // console.log(`Actualizado ${fecha.getDate()} a las ${horas} el valor de reinicio es: ${valReiniciar}`);

</script>

<style>

  #btnalert {
    border: 2px solid;
    border: none;
  }

  #btnalert:hover {
    color: rgba(255, 255, 255, 1) !important;
    box-shadow: 0 4px 16px rgb(115, 115, 115);
    transition: all 0.2s ease;
  }

  .pos {
    position: absolute;
  }

  .uti {
    background-color: #003057;
    margin: 15px 0 0 10px;
    height: 30px;
    width: 170px;
    color: white;
  }

  .u {
    background-color: orange;
    color: black;
  }

  .uta {
    background-color: #fffb3a;
    margin: 15px 0 0 10px;
    height: 30px;
    width: 170px;
    color: black;
  }

  .utr {
    background-color: #ff1a26;
    margin: 15px 0 0 10px;
    height: 30px;
    width: 170px;
    color: white;
  }
</style>

app/views/home/_alertaPerfiles.html.erb
<!--<h1 class="no-margins">0</h1>-->
<strong class="color1"><%= t('views.home_index.atendidas') %></strong>
<small class="no-margins color1"><%= Tbitacora.where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).where.not(:IdUsuario => "N/A").count %></small>
<br>
<strong class="color2"><%= t('views.home_index.no_Atendidas') %></strong>
<small class="no-margins color2"><%= Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).where(:IdUsuario => "N/A").count %></small>
<br>

<style>
  small, strong {
    font-size: medium;
  }

  .color1 { /*transaccional atendidas*/
    color: #498fc8;
    text-shadow: #498fc8;
  }

  .color2 { /*transaccional no atendidas*/
    color: #14568c;
    text-shadow: #14568c;
  }

</style>

app/views/home/_contadorSuperior.html.erb
<%
  @countTrans = Tbitacora.where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 1).count
  @countPerf = Tbitacora.where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).count

  @todas = @countTrans.to_i + @countPerf.to_i
%>
<h1 class="no-margins"><%= number_with_delimiter(@todas, :delimiter => ',') %></h1>

app/views/home/_pie2.html.erb
<%= javascript_include_tag 'jquery-ui.js' %>

<div class="ibox-content">
  <br>
  <div class="flot-chart">
    <div class="flot-chart-pie-content" id="flot-pie-chart-tran"></div>
  </div>
</div>


<script type="text/javascript">
    <% @noAtendidasTran = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 1).where(:IdUsuario => "N/A").count %>


    $(function () {
        <% if @leerNewTran == 2 || @leerConTran == 2 %>
        var data_tran = [{
            //label: "Alertas atendidas",
            //data: 1,
            data: <%= Tbitacora.where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 1).where.not(:IdUsuario => "N/A").count %>,
            color: "#498fc8",
            <% if @leerNewTran == 2 %>
            // url: window.location.href + '<%= alertn_alertTran_path %>'
            url: '<%= home_index_path %>'
            <% end %>
        }, {
            //label: "Alertas pendientes",
            //data: 100,
            data: <%= @noAtendidasTran %>,
            color: "#14568c",
            <% if @leerNewTran == 2 %>
            url: window.location.href + '<%= alertn_alertTran_path %>'
            <% end %>

        }];

        var plotObj = $.plot($("#flot-pie-chart-tran"), data_tran, {
            series: {
                pie: {
                    show: true
                }
            }

            ,
            grid: {
                hoverable: true,
                <% if @leerNewTran == 2 %>
                clickable: true
                <% end %>
            },
            tooltip: true,
            tooltipOpts: {
                content: "%p.0%", // show values
                shifts: {
                    x: 20,
                    y: 0
                },
                defaultTheme: false
            },
            legend: {
                useHTML: true,
                labelFormatter: function (label, series) {
                    return '<div style="text-align: left; width:150px;"><strong>' + label + '</strong></div><div style="width:40px; text-align:right;">Total: ' + series.data[0][1] + '</div>';
                }
            }
        });
        <% end %>

        $("#flot-pie-chart-tran").on("plotclick", function (event, pos, obj) {
            if (!obj) {
                return;
            }

            <% if @noAtendidasn != 0 %>
            window.location.href = obj.series.url;
            <% end %>
        });
    });


</script>

app/views/home/_pie3.html.erb
<%= javascript_include_tag 'jquery-ui.js' %>

<div class="ibox-content">
  <br>
  <div class="flot-chart">
    <div class="flot-chart-pie-content" id="flot-pie-chart-per"></div>
  </div>
</div>

<script type="text/javascript">

    <% @noAtendidasPer = Tbitacora.where(:IdEstado => 1).where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).where(:IdUsuario => "N/A").count %>

    $(function () {
        <% if @leerNewPer == 2 || @leerConPer == 2 %>
        var data_per = [{
            //label: "Alertas atendidas",
            //data: 112,
            data: <%= Tbitacora.where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).where.not(:IdUsuario => "N/A").count %>,
            color: "#498fc8",
            <% if @leerNewPer == 2 %>
            // url: window.location.href + '<%= alertn_alertPer_path %>'
            url: '<%= home_index_path %>'
            <% end %>
        }, {
            //label: "Alertas pendientes",
            //data: 1065,
            data: <%= @noAtendidasPer %>,
            color: "#14568c",
            <% if @leerNewPer == 2 %>
            url: window.location.href + '<%= alertn_alertPer_path %>'
            <% end %>
        }];

        var plotObj = $.plot($("#flot-pie-chart-per"), data_per, {
            series: {
                pie: {
                    show: true
                }
            }

            ,
            grid: {
                hoverable: true,
                <% if @leerNewPer == 2 %>
                clickable: true
                <% end %>
            },
            tooltip: true,
            tooltipOpts: {
                content: "%p.0%", // show values
                shifts: {
                    x: 20,
                    y: 0
                },
                defaultTheme: false
            },
            legend: {
                useHTML: true,
                labelFormatter: function (label, series) {
                    return '<div style="text-align: left; width:150px;"><strong>' + label + '</strong></div><div style="width:40px; text-align:right;">Total: ' + series.data[0][1] + '</div>';
                }
            }
        });
        <% end %>

        $("#flot-pie-chart-per").on("plotclick", function (event, pos, obj) {
            if (!obj) {
                return;
            }
            window.location.href = obj.series.url;
        });

    });



</script>

app/views/home/_totalAlerts.html.erb
<strong class="color1">Transaccional:</strong></i>
<small class="no-margins color1"><%= Tbitacora.where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 1).count %></small> <br>
<strong class="color2">Perfiles:</strong>
<small class="no-margins color2"><%= Tbitacora.where(:canceladas => 0).where(:IdTipoReg => 3).where(:IdProducto => 2).count %></small> <br>

<style>
  small, strong {
    font-size: medium;
  }

  .color1 {
    color: #498fc8;
    text-shadow: #498fc8;
  }

  .color2 {
    color: #14568c;
    text-shadow: #14568c;
  }

</style>

<script>
  console.log("total contador abajo")
</script>